//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shim_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarsRentals = new HashSet<CarsRental>();
        }
    
        public int CarNumber { get; set; }
        public int ModelCode { get; set; }
        public decimal Mileage { get; set; }
        public string CarImage { get; set; }
        public bool Available { get; set; }
    
        public virtual CarsModel CarsModel { get; set; }
        public virtual ICollection<CarsRental> CarsRentals { get; set; }
    }
}
