//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shim_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsRental
    {
        public int CodeCarRental { get; set; }
        public int CarNumber { get; set; }
        public int UserIDCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
