//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shim_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsModel
    {
        public CarsModel()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int ModelCode { get; set; }
        public int ManufacturerCode { get; set; }
        public string ModelName { get; set; }
        public int Year { get; set; }
        public bool Gear { get; set; }
        public decimal DailyRentalCost { get; set; }
        public decimal DailyLateReturnCost { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
