//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shim_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.CarsModels = new HashSet<CarsModel>();
        }
    
        public int ManufacturerCode { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual ICollection<CarsModel> CarsModels { get; set; }
    }
}
